version: "3.8"

services:
  app:
    build: .
    container_name: t3-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: pnpm dev
